//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ticket_tracker.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aplicativo
    {
        public Aplicativo()
        {
            this.Incidencias = new HashSet<Incidencia>();
            this.Usuarios = new HashSet<Usuario>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Descrpcion { get; set; }
        public int Id_tipo { get; set; }
        public int Id_estado { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Tipo_aplicativo Tipo_aplicativo { get; set; }
        public virtual ICollection<Incidencia> Incidencias { get; set; }
        public virtual ICollection<Usuario> Usuarios { get; set; }
    }
}
