//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ticket_tracker.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estado
    {
        public Estado()
        {
            this.Aplicativos = new HashSet<Aplicativo>();
            this.Roles = new HashSet<Role>();
            this.Usuarios = new HashSet<Usuario>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Aplicativo> Aplicativos { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
        public virtual ICollection<Usuario> Usuarios { get; set; }
    }
}
