//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ticket_tracker.Modelos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class proyecto_finalEntities : DbContext
    {
        public proyecto_finalEntities()
            : base("name=proyecto_finalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aplicativo> Aplicativos { get; set; }
        public virtual DbSet<Estado> Estados { get; set; }
        public virtual DbSet<Incidencia> Incidencias { get; set; }
        public virtual DbSet<Prioridad> Prioridads { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Tipo_aplicativo> Tipo_aplicativo { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
