//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ticket_tracker.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incidencia
    {
        public Incidencia()
        {
            this.Incidencias1 = new HashSet<Incidencia>();
        }
    
        public int Id { get; set; }
        public int Id_aplicativo { get; set; }
        public int Id_usuario { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime Fecha_estimada { get; set; }
        public int Id_prioridad { get; set; }
        public int Id_estado { get; set; }
        public Nullable<int> Id_incidencia_papa { get; set; }
    
        public virtual Aplicativo Aplicativo { get; set; }
        public virtual Prioridad Prioridad { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Incidencia> Incidencias1 { get; set; }
        public virtual Incidencia Incidencia1 { get; set; }
        public virtual Estado Estado { get; set; }
    }
}
