//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ticket_tracker.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Incidencias = new HashSet<Incidencia>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public System.DateTime Fecha_nacimiento { get; set; }
        public int Id_estado { get; set; }
        public int Id_rol { get; set; }
        public string Contrasena { get; set; }
        public string NombreUsuario { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual ICollection<Incidencia> Incidencias { get; set; }
        public virtual Role Role { get; set; }
        public virtual Aplicativo Aplicativo { get; set; }
    }
}
